# Generated by Django 3.1.3 on 2020-12-06 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default_logo.png', null=True, upload_to='images/')),
                ('gender', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
