# Generated by Django 3.1.3 on 2020-12-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Establishment',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
