# Generated by Django 3.1.3 on 2020-12-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201206_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Establishment',
        ),
    ]
