# Generated by Django 3.1.3 on 2020-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
