# Generated by Django 3.1.3 on 2020-12-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studfood', '0003_auto_20201206_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
