# Generated by Django 3.1.3 on 2020-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studfood', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='category',
            field=models.ManyToManyField(null=True, to='studfood.category'),
        ),
    ]
