# Generated by Django 3.1.3 on 2020-12-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studfood', '0011_foodmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacter_nous',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacter_nous',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacter_nous',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacter_nous',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
